version: '3'
services:
  server:
    image: node
    build: ./
    command: node app/server.js -d
    ports:
      - "3000:3000"
  js:
    build: ./
    command: npm test
    volumes:
      - .:/app
  php:
    build: ./php
    command: ./vendor/bin/phpunit --bootstrap vendor/autoload.php StackTest
    volumes:
      - ".:/php"