version: '3'
services:
  server:
    build: ./
    command: node app/server.js
    ports:
      - "3000:3000"
  js:
    build: ./
    volumes:
      - .:/app
    depends_on:
      - server
  php:
    build: ./php
    volumes:
      - ".:/php"